config/routes.rb
Rails.application.routes.draw do
    
  resources :articles do
    resources :comments
  end

  resources :companies do
    collection { post :import }
  end

  devise_for :users
  resources :listings do
    resources :orders, only: [:new,:create]
  end
  
  resources :invoices
  
  get 'pages/about'
  get 'pages/contact'
  get 'seller' => 'listings#seller'
  get 'sales' => 'orders#sales'
  get 'purchases' => 'orders#purchases'

  root to: 'listings#index'

end

app/models/listing.rb
class Listing < ActiveRecord::Base
  if Rails.env.development?
    has_attached_file :image, 
                    styles: { medium: "200x", thumb: "100x100>" },
                    default_url: "/assets/images/:style/default.jpg"
  else
    has_attached_file :image, 
                    styles: { medium: "200x", thumb: "100x100>" },
                    default_url: "/assets/images/:style/default.jpg",
                    :storage => :dropbox,
                    :dropbox_credentials => Rails.root.join("config/dropbox.yml"),
                    :path => ":style/:id_:filename"
  end
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  
  validates :name, :description, :price, presence: true
  validates :price, numericality: { greater_than: 0 }
  validates_attachment_presence :image  

  default_scope { order(created_at: :desc) }

  belongs_to :user
  has_many :orders
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:seller, :new, :create, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  def seller
    @listings = Listing.where(user: current_user)
  end

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render :show, status: :created, location: @listing }
      else
        format.html { render :new }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { render :show, status: :ok, location: @listing }
      else
        format.html { render :edit }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image)
    end

    def check_user
      if current_user != @listing.user
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for @listing, html: { multipart: true } do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :image %>
    <%= f.file_field :image ,class: "form-control"%>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing Listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing, class: "btn btn-link" %> |
<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/index.html.erb
<div class="jumbotron">
  <h1>FakeStore items</h1>
  <h2>Listings elements</h2>
</div>
<div class="center">
  <div class="row">
    <% @listings.each do |listing| %>
      <div class="col-md-3">
        <div class="thumbnail">
          <%= link_to image_tag(listing.image.url), listing %>
          <div class="caption">
            <h3><%= listing.name %></h3>
            <p><%= number_to_currency(listing.price) %></p>
            <p><%= "Sold by #{listing.user.name}" %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<br>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link" %>
<% end %>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/seller.html.erb
<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Image</th>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Date</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
    <% @listings.each do |listing| %>
      <tr>
        <td><%= image_tag listing.image.url(:thumb) %></td>
        <td><%= listing.name %></td>
        <td><%= listing.description %></td>
        <td><%= number_to_currency(listing.price) %></td>
        <td><%= listing.created_at.strftime("%d/%m/%Y") %></td>
        <td>
          <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              Action
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu">
              <li><%= link_to "View", listing, class: "btn btn-link" %></li>
              <li><%= link_to "Edit", edit_listing_path(listing), class: "btn btn-link" %></li>
              <li><%= link_to "Destroy", listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></li>
            </ul>
          </div>
        </td>
      </tr>
    </tbody>
  <% end %>
</table>
<br>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class:"btn btn-link" %>
<% end %>

app/views/listings/show.html.erb
<div class="row">
  <div class="col-md-6">
  <div class="thumbnail">
    <%= image_tag @listing.image.url %>
  </div>
  </div>
  <div class="col-md-6">
    <h3><%= @listing.name %></h3>
    <p><%= number_to_currency(@listing.price) %></p>
    <p><%= @listing.description %></p>
    <br>
    <div class="center">
      <% if current_user != @listing.user%>
        <%= link_to 'Buy it now', new_listing_order_path(@listing), class: "btn btn-primary", data: { no_turbolink: true } %>
      <% end %>      
    </div>
  </div>
</div>

<% if current_user == @listing.user%>
  <%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> |
<% end %>
<%= link_to 'Back', listings_path, class: "btn btn-link" %>