config/routes.rb
Rails.application.routes.draw do
    
  resources :articles do
    resources :comments
  end

  resources :companies do
    collection { post :import }
  end

  devise_for :users
  resources :listings do
    resources :orders, only: [:new,:create]
  end
  
  resources :invoices
  
  get 'pages/about'
  get 'pages/contact'
  get 'seller' => 'listings#seller'
  get 'sales' => 'orders#sales'
  get 'purchases' => 'orders#purchases'

  root to: 'listings#index'

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  validates :company, :tax, :salesperson, presence: true
  validates :tax, numericality: { greater_than: 0 }
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoice, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  # GET /invoices
  # GET /invoices.json
  def index
    #@invoices = Invoice.all
    @search = InvoiceSearch.new(params[:search])
    @invoices = @search.scope
  end

  # GET /invoices/1
  # GET /invoices/1.json
  def show
  end

  # GET /invoices/new
  def new
    @invoice = Invoice.new
  end

  # GET /invoices/1/edit
  def edit
  end

  # POST /invoices
  # POST /invoices.json
  def create
    @invoice = Invoice.new(invoice_params)

    respond_to do |format|
      if @invoice.save
        format.html { redirect_to @invoice, notice: 'Invoice was successfully created.' }
        format.json { render :show, status: :created, location: @invoice }
      else
        format.html { render :new }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invoices/1
  # PATCH/PUT /invoices/1.json
  def update
    respond_to do |format|
      if @invoice.update(invoice_params)
        format.html { redirect_to @invoice, notice: 'Invoice was successfully updated.' }
        format.json { render :show, status: :ok, location: @invoice }
      else
        format.html { render :edit }
        format.json { render json: @invoice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invoices/1
  # DELETE /invoices/1.json
  def destroy
    @invoice.destroy
    respond_to do |format|
      format.html { redirect_to invoices_url, notice: 'Invoice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invoice
      @invoice = Invoice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def invoice_params
      params.require(:invoice).permit(:company, :tax, :salesperson)
    end
end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<%= form_for(@invoice) do |f| %>
  <% if @invoice.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4><%= pluralize(@invoice.errors.count, "error") %> prohibited this invoice from being saved:</h4>

      <ul>
      <% @invoice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :company %>
    <%= f.text_field :company, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :tax %>
    <%= f.text_field :tax, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :salesperson %>
    <%= f.text_field :salesperson, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/invoices/edit.html.erb
<h1>Editing Invoice</h1>

<%= render 'form' %>

<%= link_to 'Show', @invoice %> |
<%= link_to 'Back', invoices_path %>

app/views/invoices/index.html.erb
<div class="row">
  <div class="pull-right range-query">
    <%= form_tag invoices_path, method: :get do %>
    <%= text_field_tag 'search[date_from]', @search.date_from %>
    <%= text_field_tag 'search[date_to]', @search.date_to %>
    <%= submit_tag 'Search', class: "btn search-button" %>
    <% end %>
    <br>
  </div>
</div>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Date</th>
      <th>Company</th>
      <th>Tax</th>
      <th>Salesperson</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @invoices.each do |invoice| %>
      <tr>
        <td><%= invoice.created_at.strftime("%d/%m/%Y") %></td>
        <td><%= invoice.company %></td>
        <td><%= invoice.tax %></td>
        <td><%= invoice.salesperson %></td>
        <td>
          <div class="dropdown">
            <button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenu" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
              Action
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenu">
              <li><%= link_to "View", invoice, class: "btn btn-link" %></li>
              <li><%= link_to "Edit", edit_invoice_path(invoice), class: "btn btn-link" %></li>
              <li><%= link_to "Destroy", invoice, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></li>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
  <%= link_to 'New Invoice', new_invoice_path, class:"btn btn-link" %>
<% end %>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>

<%= render 'form' %>

<%= link_to 'Back', invoices_path, class: "btn btn-link" %>

app/views/invoices/show.html.erb
<div class="row">
  <div class="col-md-6">
    <h3><%= @invoice.company %></h3>
    <p>
      <strong>Date:</strong>
      <%= @invoice.created_at.strftime("%d/%m/%Y") %>
    </p>
    <p>
      <strong>Tax:</strong>
      <%= @invoice.tax %>
    </p>
    <p>
      <strong>Salesperson:</strong>
      <%= @invoice.salesperson %>
    </p>
  </div>
</div>

<%= link_to 'Edit', edit_invoice_path(@invoice), class: "btn btn-link" %> |
<%= link_to 'Back', invoices_path, class: "btn btn-link" %>