config/routes.rb
Rails.application.routes.draw do
    
  resources :articles do
    resources :comments
  end

  resources :companies do
    collection { post :import }
  end

  devise_for :users
  resources :listings do
    resources :orders, only: [:new,:create]
  end
  
  resources :invoices
  
  get 'pages/about'
  get 'pages/contact'
  get 'seller' => 'listings#seller'
  get 'sales' => 'orders#sales'
  get 'purchases' => 'orders#purchases'

  root to: 'listings#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, :body, presence: true

  default_scope { order(created_at: :desc) }

  belongs_to :user

  has_many :comments, dependent: :destroy
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :check_user, only: [:edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    #@article = Article.find(params[:id])
    @comment = @article.comments.build
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.build(article_params)

    respond_to do |format|
      if @article.save
        # format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.html { redirect_to articles_path, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body)
    end

    def check_user
      if current_user != @article.user
        redirect_to root_url, alert: "Sorry, this article belongs to someone else"
      end
    end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for [@article], :html=> { class: "form-horizontal", role: "form" } do |f| %>
  <% if @article.errors.any? %>
    <%= render 'shared/error_messages', object: @article %>
  <% end %>

  <div class="form-group">
    <div class="col-md-2">
      <%= f.label :title %>
    </div>
    <div class="col-md-4">
      <%= f.text_field :title, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-2">
      <%= f.label :body %>
    </div>
    <div class="col-md-4">
      <%= f.text_area :body, rows: 10 , class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-md-offset-3 col-md-9">
      <%= f.submit class: "btn btn-success" %>
    </div>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="row">
    <%= link_to 'Back', articles_path, class: "btn btn-default" %>
    <%= link_to 'Show', @article, class: "btn btn-primary btn-lnk" %>
</div>
<h2 class="center">Editing Article</h2></br>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="center">Listing Articles</h1>

<div class="row">
  <div class="col-md-12">
      <% if user_signed_in? %>
        <%= link_to 'New Article', new_article_path, class: "btn btn-link", id: "new-article-btn" %>
      <% end %>
      <% @articles.each do |article| %>
      <div class="well well-lg">
        <div class="article">
          <h2><%= link_to article.title, article_path(article)%></h2>
        </div>
        <div class="article-body">
          <%= truncate(article.body, length: 500) %>
        </div>
        <div class="author">
          <small>Created by: <%= article.user.email %></small>
        </div>
      </div>
      <% end %>
  </div>
</div>

app/views/articles/new.html.erb
<div class="row">
  <%= link_to 'Back', articles_path, class: "btn btn-default" %>
</div>
<h2 class="center">New Article</h2>

<%= render 'form' %>

app/views/articles/show.html.erb
<div class="row">
  <div class="col-md-10">
  <%= link_to 'Back', articles_path, class: "btn btn-default" %>
    <article class="detail-article">
      <h1 class="article-detail-title"><%= @article.title %></h1>
      <div class="glyphicon glyphicon-calendar" id="article-date">
        <%= @article.created_at.strftime("%b %d, %Y") %>
      </div>
      <div class="article-body">
        <%= @article.body %>
      </div>
    </article>
      <% if user_signed_in? && current_user == @article.user %>
        </br>
        <%= link_to 'Edit Article', edit_article_path(@article), class: "btn btn-warning" %>
        <%= link_to 'Destroy Article', article_path(@article), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %>
      <% end %>
    <%= render 'comments/form' %>
    <%= render 'comments/listing_comments' %>
  </div>
</div>