config/routes.rb
Rails.application.routes.draw do
    
  resources :articles do
    resources :comments
  end

  resources :companies do
    collection { post :import }
  end

  devise_for :users
  resources :listings do
    resources :orders, only: [:new,:create]
  end
  
  resources :invoices
  
  get 'pages/about'
  get 'pages/contact'
  get 'seller' => 'listings#seller'
  get 'sales' => 'orders#sales'
  get 'purchases' => 'orders#purchases'

  root to: 'listings#index'

end

app/views/layouts/_footer.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-10 text-center">
      <footer role="contentinfo">
        <p><small>Copyright</small></p>
      </footer>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">FakeStore</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
          <li class="active"><%= link_to "Home", root_path %><span class="sr-only">(current)</span></li>
          <li><%= link_to "About us", pages_about_path %></li>
          <li><%= link_to "Contact", pages_contact_path %></li>
          <% if user_signed_in? %>
            <li><%= link_to "Invoices", invoices_path %></li>
            <li><%= link_to "Companies", companies_path %></li>
          <% end %>
          <li><%= link_to "Articles", articles_path %></li>
          <li><%= link_to "Listings", listings_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Seller account <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Manage Listings", seller_path %></li>
            <li><%= link_to "Sales History", sales_path %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Purchase History", purchases_path %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>       
      <% else %>
      <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Log In", new_user_session_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_messages.html.erb
<% flash.each do |name,msg| %>
  <%if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == "notice" ? "success" : "danger" %> alert-dismissible" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FakeStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'https://js.stripe.com/v2/'%>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>